/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CSCC;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class App {

    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        logger.info("Please provide logfile.txt file path: ");
        try {
            String dbpath = reader.readLine();
            logger.debug("File path read: " + dbpath);
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }

    }
}
