/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CSCC;

import CSCC.data.Event;
import CSCC.processing.EventHandler;
import CSCC.processing.JsonParser;
import org.apache.commons.io.FileUtils;
import org.apache.commons.io.LineIterator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class App {

    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {

        logger.info("Reading user input.");
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in))) {
            logger.info("Please provide logfile.txt file path: ");
            String dbpath = reader.readLine();
            logger.debug("File path read: " + dbpath);
            logger.info("Processing logfile entries.");
            LineIterator li = FileUtils.lineIterator(FileUtils.getFile(dbpath));
            JsonParser jsonParser = new JsonParser();
            EventHandler eventHandler = new EventHandler();
            while (li.hasNext()) {
                String jsonLine = li.nextLine();
                logger.debug("Line read from file: " + jsonLine);
                Event event = jsonParser.retrieve(jsonLine);
                logger.debug("Parsing result: " + event.toString());
                eventHandler.process(event);
            }
            li.close();
        } catch (IOException ioe) {
            logger.error(ioe.getMessage());
        }
        logger.info("Processing has been finished.");
    }
}
